### ISSUE TITLE
Allow pass all props to root div

### ISSUE THREAD

**Issue by minipai** [airbnb/react-outside-click-handler#14] opened 2018-09-22 05:27 UTC
Hi,
Would you consider allow pass all props other than default ones to root div?
My use case is pass className.

I can make a PR for it.

**Comment by ljharb** [comment] 2018-09-22 05:31
Duplicate of #13; duplicate of #8; duplicate of #2.

https://brigade.engineering/don-t-pass-css-classes-between-components-e9f7ab192785 is a good read.

**Closed by ljharb** 2018-09-22 05:31 UTC
