### ISSUE TITLE
Ability to pass props to `div` element

### ISSUE THREAD

**Issue by quolpr** [airbnb/react-outside-click-handler#23] opened 2019-03-05 08:45 UTC
Hi! Nice library, works very well. But, could it pass all props to `div` element, like `className`? At least it will give the ability to work more flexible with the styled-component.

Suppose we have such component:
```
const MyBody = styled.div``;
cont MyComponent = () => {
  return (
    <OutsideClickHandler>
      <MyBody />
    </OutsideClickHandler>
  );
}

export const ListOfComponents = () => {
  return(
    <>
      <MyComponent />
      <MyComponent />
      <MyComponent />
    </>
  );
}
```

Then, it will be pretty hard to add gap between `MyComponent` in `ListOfComponents`. But with props passing it will be fixed easily:

```
const MyBody = styled.div``;
cont MyComponent = () => {
  return (
    <OutsideClickHandler>
      <MyBody />
    </OutsideClickHandler>
  );
}

cosnt MyComponentStyled = styled(MyComponent)`
  & + & {
    margin-top: 20px;
  }
`;

export const ListOfComponents = () => {
  return(
    <>
      <MyComponentStyled />
      <MyComponentStyled />
      <MyComponentStyled />
    </>
  );
}
```

**Comment by lencioni** [comment] 2019-03-05 16:40
I think this has been discussed before: #2, #8, #13, #14, #21. Are any of those helpful for you?

**Comment by ljharb** [comment] 2019-03-05 18:30
Closing as a dupe, but please feel free to keep discussing here!

(Duplicate of #2. Duplicate of #8. Duplicate of #13. Duplicate of #14. Duplicate of #21).

**Closed by ljharb** 2019-03-05 18:30 UTC

**Comment by quolpr** [comment] 2019-03-05 20:06
I read the article, I totally agree with all of the points. But sometime in very rare cases you **really** need to pass style/classname to this div element. As example you can see it at #21

But the problem is that ReactOutsideClickHandler is not a usual thing like button. And the ideal implementation should not create any `div` elements, cause it is not expecting that it will affect on markup flow in some way.

But, it creates `div` element that can break markup flow, and developer need the ability to control this to avoid any issues

PS: I totally understand why `div` is needed and I'm not against of it
