### ISSUE TITLE
className for the wrapping div

### ISSUE THREAD

**Issue by ryabv** [airbnb/react-outside-click-handler#49] opened 2021-01-13 09:38 UTC
Could you add a className prop? It will really helpful in some cases

**Comment by ljharb** [comment] 2021-01-13 15:18
No, this is very intentional - see https://github.com/airbnb/react-outside-click-handler/issues/13#issuecomment-423205690 and https://github.com/airbnb/react-outside-click-handler/issues/8#issuecomment-408947995 and https://github.com/airbnb/react-outside-click-handler/issues/2#issuecomment-394891534.

Duplicate of #35. Duplicate of #33.

**Closed as completed by ljharb** 2021-01-13 15:18 UTC
